### ISSUE TITLE
Add option to use non-AMOLED dark theme 

### ISSUE THREAD

**Issue by BayLee4** [mollyim/mollyim-android#128]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

Hi,
Molly changed the default background color for the dark theme from [#1B1C1F](https://github.com/signalapp/Signal-Android/blob/main/app/src/main/res/values/material3_colors_dark.xml#L9) to [#000000](https://github.com/mollyim/mollyim-android/blob/main/app/src/main/res/values/material3_colors_dark.xml#L9) (I guess to match the system AMOLED black style, removed since Android 12). Would it be possible to have an option to use the original background color? For some reason I find it more difficult to read with the pure black theme. Thank you!

**Comment by BayLee4** [comment]
Or alternatively and more simply, would reverting the background color to [#1B1C1F](https://github.com/signalapp/Signal-Android/blob/main/app/src/main/res/values/material3_colors_dark.xml#L9) be an acceptable solution?

**Comment by valldrac** [comment]
You're right. Molly should keep the original background color for easy readability. But many Molly users already love the true black theme.

It would be awesome if someone can contribute to this feature. We need to add a 2nd dark theme and develop an script to sync them. A gradle task preferably. This would fix the burden of maintaining an additional theme.

**Comment by xIUPITERx** [comment]
The question is, should we wait until signal implements material you theming?

**Comment by Cod3dDOT** [comment]
Any updates on this?

**Comment by Uneccessary** [comment]
Hey, I personally love the true black background and couldn't live without it, but my friend would like to have original one, how hard would it be to add a 3 option?

**Comment by ThatOneCalculator** [comment]
> The question is, should we wait until signal implements material you theming?

I don't think they'll ever add it... It'd be nice if Molly added Material You, since MD3 is already used

**Comment by valldrac** [comment]
Seems like the AMOLED theme could be improved as well. Someone on [Twitter](https://twitter.com/s8n_ru/status/1764773682428166548) reported it.

**Comment by Uneccessary** [comment]
:eyes:

**Comment by itsmartashub** [comment]
Oh my, what's the reason behind removing the AMOLED theme? Was there too much pressure from users to revert to the original color? Or perhaps you sensed that Signal may soon implement dynamic Material You, so you avoided the hassle and demands from users that could arise from that? Is there any plan to introduce an + OLED theme (again) in the near future, or is that it? Honestly, this is one of the main reasons why I use Molly, deng 😭

**Comment by itsmartashub** [comment]
> Must say that the only reason why I don't use molly on all my devices is the oled theme.

Sorry, I just find this funny because it seems like your Github profile picture is AMOLED (completely black)? 😭

**Comment by valldrac** [comment]
There are several reasons why we decided to remove this feature. We've been discussing them in our Matrix channel lately. Basically, everyone agrees that true black background should be optional, meaning we should add a second dark theme to the app. This is because AMOLED-friendly themes goes against the industry trend and affects the usability for many users, as seen in this issue report.

The question now goes around the cost of implementing a second dark theme in Molly. With the current theme system, it's messy and the maintenance costs are high. This might improve in the future, and if there's still demand for this feature, we'll consider reintroducing it. But this time, it'll be done properly, as an optional choice. If any developer wants to step up, implement, and maintain this feature, we'd love to have it back.

The background color we picked for the dark theme isn't pure black, but it's not as brightness as Signal's original. It's a bit darker.

Thanks for your understanding!
