### ISSUE TITLE
Please provide instructions for migrating from Signal

### ISSUE THREAD

**Issue by owenh000** [mollyim/mollyim-android#153]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

Hi! This is a *documentation* feature request.

Signal users who are interested in migrating to Molly may have concerns about exactly what steps to take to successfully migrate. There are several moving parts, including Signal account registration, PINs, passphrases, and chat backups.

I have already written a list of steps and would like to suggest adding this information as a separate section in the `README.md` file. Please see the pull request which I will open shortly.

Thank you for your work on Molly and Molly-FOSS.

**Comment by valldrac** [comment]
Good idea! Lets discuss the details in the pull-request.

**Comment by ngrigoriev** [comment]
I tried to follow the guide "Migrating from Signal" (https://github.com/mollyim/mollyim-android/wiki/Migrating-From-Signal) but, turns out, it was a partial success.

After a while, I started getting the warning popups on my Linux desktop app - about the need to sign in to the Signal app on the mobile phone. I actively and daily use Molly on my Android and the desktop app as well. Luckily, I still have the old phone, without the SIM card, of course, and Signal there is working - so I was able to push the deadline. But it happened again, so I am looking for more permanent solution :)

Right now Molly and desktop Signal work fine. Molly shows two connected devices - the phone itself (normal?) and the desktop app.

Using Molly-FOSS on GrapheneOS. Everything latest.
