### ISSUE TITLE
Molly automatically closes itself

### ISSUE THREAD

**Issue by ryu0q** [mollyim/mollyim-android#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When I exit Molly, After a few minutes it automatically closes itself without me doing anything, even if I have battery optimizations disabled.

### Steps to reproduce

1. Open Molly
2. Type password to decrypt database
3. After it successfully unlocks, close Molly
4. Wait a few minutes while staring at the notification panel and it can be seen that `Molly is unlocked` disappears from he notification panel, indicating it has either crashed or closed itself.

### Molly version

v6.3.6-1

### Android version

Android 10

### Device

Galaxy S8+ (with Note9 custom ROM)

### Link to debug log

https://debuglogs.org/android/6.3.6/ccbd9206106cca42ee8694e9d05bbfea8c1faf2fcfe5f28a1557d14f1143235b

**Comment by valldrac** [comment]
Molly is configured with a auto-lock timeout of 0 seconds, so it will lock when the phone goes to sleep. You can set a higher value in the Settings -> Privacy menu.

Historically, when the phone went to sleep mode by user input inactivity, the screen was turned off too. This is not true anymore. Android may enter into sleep mode internally before you notice anything.

I see Molly's documentation can be misleading in that sense. I take note to improve it. Thanks for reporting the issue.

**Comment by abdo2048** [comment]
Hi there, I don't know if this related or not, but I made a phone call through Molly, and my screen timeout in my Samsung (A54 5G) settings is set to 2 minutes, and I noticed two things:
1. The screen doesn't turn off when I put phone on my ear during the call (Which should be the normal behavior when making phone calls)
2. After 2 minutes of the call, the screen goes off (because I of internal phone settings as mentioned) and the call ended! And when I turn the screen on, I see blank white screen and when I press back button it doesn't exist the app, I have to close the app from all apps button and start again Molly app. Also, in the second time where Molly turns into white screen, I closed it so that I start it again and make the call again, but I had to start the app multiple times because each time I start it, I see the white screen!

To continue my call, I had to set screen timeout in internal phone settings to 10 minutes (I don't know why my Samsung doesn't has more then 10 minutes limit!), and if I will go beyond 10 minutes in the call, I try to touch the screen with my finger to wake it up and reset the 10 minutes time.

Note: I have the database decryption enabled.
App version: v6.4.3-2FOS .. Android version: 13
Here is the debug log: https://debuglogs.org/android/6.41.3/c48266f3757f649f0f4ad1010d8ac9d5f7e6e4f96bd11bf58108ea67605b432a

Note: This phone is new, and de bloated all recommended app by Universal Android Debloater:
[universal-android-debloater](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation)
I didn't insert a sim it yet in the phone to test if the issue I pointed out in number (1) is happening in normal sim phone calls or not, but I'll let you know.

**Comment by valldrac** [comment]
@abdo2048: Seems it's related yeah, but could you please open a specific ticket for the issue you're mentioning? So we can track it property.

**Comment by abdo2048** [comment]
**Update:**
Later (with same configuration/version), I made another call and the screen goes off normally when I put my phone on my ear! This time I was wearing hoodie (hoodie with hood).
It looks like there is something at my end that prevents light sensor from working properly, I mean it could be the screen protector.

But, if we said this is solved, we still have the problem where Molly closes itself and screen turns white when the screen timeout goes off (I mean for example when speaker is on and we didn't put the phone on the ear).
I will test this case one more time and open new issue for it if it happens again.
