### ISSUE TITLE
Molly crashes while restoring encrypted backup file

### ISSUE THREAD

**Issue by straightshark** [mollyim/mollyim-android#173]

**Comment by straightshark** [comment]
@bepaald can you please help me with this?
i have no idea how to use your tool as i am not that good with computers

**Comment by bepaald** [comment]
Yeah sure, I'll try. Not sure if the molly-devs like this going on in their issue tracker, maybe you should open an issue on my github if they let you know.

First of all, your passphrase is absolutely correct, otherwise it would never decrypt 800 messages.

Now, we need to know why Molly crashes. The best thing to do would be to get a debug log from Molly, but if that is too difficult you could indeed try signalbackup-tools.

I am assuming you're on windows.

First, download the tool from my github here: https://github.com/bepaald/signalbackup-tools/releases
Save it somewhere together with the backup file, for example in `C:`, create a folder `signalbackup-tools` and put the program and backup file in there.
Then start a command prompt (run -> 'cmd.exe'), change to the directory to where you saved the program (`cd C:\signalbackup-tools`) and run it by typing `signalbackup-tools_win.exe [backupfile] [passphrase] --checkdbintegrity`. And let me know the output.
