### ISSUE TITLE
Do not bypass system DNS

### ISSUE THREAD

**Issue by BayLee4** [mollyim/mollyim-android#228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

My firewall catched Molly bypassing the system DNS using its own hardcoded [DoH resolvers](https://github.com/mollyim/mollyim-android/blob/ffc60007942c93c68c6b40200a3566848ce6af8a/app/src/main/java/org/thoughtcrime/securesms/net/Network.kt#L83-L97). I cannot stress enough how I do not want that to happen, especially when it is advertised nowhere and with no way to disable it. Honestly, this is malware-like behavior.

Important to note that when in proxy mode it does not even attempt to proxy DNS requests at all, it just force the use of these embedded DNS.

With AMOLED dark mode also being forced with no way to disable it too (#128), that's enough for me to uninstall the application.

### Molly version

Latest

**Comment by valldrac** [comment]
Here's how it works:

1. If Molly doesn't have a proxy set up, it first tries the system's DNS. If that doesn't give any results or is wrong, it fallbacks to using DoH resolvers. This is to work in some environments that censors Signal blocking DNS.
2. With a proxy configured, Molly only resolves using DoH, but it always forwards the requests through the proxy.

For the first scenario, if you don't want it to resolve through DoH, just block the connections in the firewall. As long as the system DNS resolves correctly, there won't be any issues.

As for the second scenario, there's no solution. Molly uses SOCKS (TCP-only) proxies and it needs to tunnel the DNS requests somehow; it can't use the system DNS because it would cause a DNS leak.
