### ISSUE TITLE
"Verify your Signal PIN" stuck in endless loop

### ISSUE THREAD

**Issue by ilu33** [mollyim/mollyim-android#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

The "Verify your Signal PIN" window is stuck in the middle of the screen. I can click it, enter the correct PIN, but the windows stays and the app becomes unresponsive. Restarting the app results in again displaying the "Verify your Signal PIN" window.

### Steps to reproduce

1. Install Molly-Foss from the Molly repo
2. Start Molly-Foss
3. Register
4. Use the app until the "Verify your Signal PIN" event displays for the first time
5. Get stuck or disable PIN reminder.

### Molly version

v6.35.3-1 FOSS and before

### Android version

9, custom ROM

### Device

Moto G4

### Link to debug log

It's not clear whether I can review the debug log before sending it - that's why I have disabled the log function.

**Comment by muellerto** [comment]
I found this in the original Signal. And I have had it there over several releases. Indeed this is the main reason why I don't use the original Signal anymore. It's probably not a Molly problem.

**Comment by valldrac** [comment]
@muellerto Thanks for letting us know about this.

Could you please share the Signal version you were using when you last found this issue, or if you remember roughly when it happened?

**Comment by muellerto** [comment]
I had this in all Signal releases since ... don't remember ... 6.37 (?) or so, or even earlier, quiet for a while. And I think it's still there. I don't have a Signal currently, but when I install a new one I have it immediately.

The dialog for verifying the PIN doesn't have any control for a successful confirmation, there's only a cancel button. When it still did work I switched the PIN verification always off, but since the dialog behaves like this I can't anymore. So the PIN verification must remain on and that's indeed annoying because this number is rather useless but gets an importance here it never had.

This happens also in recent Langis releases.

My device is a Fairphone 3+ running /e/ 1.19.1 on Android 12.

**Comment by valldrac** [comment]
>  I don't have a Signal currently, but when I install a new one I have it immediately.

If you install it and still encounter the error, please capture the debug log (in Settings > Help) and post the link here, or send it to support@molly.im. I'll report the bug to Signal.

> When it still did work I switched the PIN verification always off, but since the dialog behaves like this I can't anymore. So the PIN verification must remain on and that's indeed annoying because this number is rather useless but gets an importance here it never had.

At least with Molly, it doesn't ask you to confirm the PIN to turn off the reminder.
