### ISSUE TITLE
Restore error: Backup could not be read

### ISSUE THREAD

**Issue by encrus** [mollyim/mollyim-android#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I created a backup from Molly on older phone to new phone

Old phone : 
    Molly version : v5.50.4-1
    Android version : 9

New phone : 
    Molly version : v6.40.4-1-FOSS
    Android version : 13

While setting up molly on the new phone I chose the following option 
"Restore from backup" and selected the file that I created as backup from the old phone (transferred the file to new phone),
but I get the error message : 
"Backup could not be read"

The file name of the backup was molly-2023-11-19-08-36-49.backup  (I am sharing this info, in case I have to do some
renaming of the file before restoring but I doubt it)

Pls help restore the backup and fix this bug. 
If I am doing something wrong, can you pls correct me and give the right steps. 

### Steps to reproduce

1.
2.

I have described this above

### Molly version

v6.40.4-1-FOSS

### Android version

Android 13

### Device

Samsung Galaxy S23

**Comment by valldrac** [comment]
It seems like the app doesn't have the permissions to read the backup file.

Let's try moving the backup file to a different location on your new phone. Also make sure Molly has the necessary permissions to access files on your phone. Check the app settings and grant any permissions to access the storage.

Please note that importing a backup from version v5.50.4 may not work due to a bug in Signal, see #209.
