### ISSUE TITLE
"Newer" backups incompatible

### ISSUE THREAD

**Issue by abh-oss01** [mollyim/mollyim-android#26]
Hi, and thanks for all the great work so far on Molly.

I just downloaded `v5
0.8.2-FOSS` from gh releases, and tried restoring a backup from my `/storage/emulated/0/sig-bkps` but molly could not import the BIN and it said it can't import backups from newer versions of signal, I have Signal `v5.2.0`, so guess that makes sense.
See screenshot below

And I know it's been really hard to keep up with the huge recent trove of upstream updates, and they're quite fast!

And please keep in mind that there is no hurry whatsoever to hurry up and release updates for molly whatsoever, we can and will wait for fully stable updates with all issues fixed and negligible bugs than upstream, assuming upstream overlooks them in the process of releasing updates quickly, so please take your time.

![20210115_212338.jpg](https://user-images.githubusercontent.com/56572179/104749507-e6837900-5778-11eb-8902-98628484c655.jpg)

**Comment by valldrac** [comment]
You are right. You have to wait until Molly gets to v5.2.0. I guess you are running Signal beta, because the latest stable now is v5.1.9. I use this [site](https://www.apkmirror.com/apk/signal-foundation/) to track their releases.

Molly v5.1.9 will be released this weekend. It's already merged in master, so it's a matter of testing and fine-tuning the new proxy functionality.

I'd rather be cautious and merge only stable releases, not cutting edge releases, because what you said. In general, the delay between the Signal and Molly releases ranges from 1 day to 15 days. On holidays, I can relax a bit, but my goal is two weeks at most.

Let me close this ticket now, but we can continue this conversation here if you want to comment something else.

**Comment by valldrac** [comment]
Not yet. I thought people would get confused with Molly's passphrase lock. Maybe I can bring it back.

**Comment by abh-oss01** [comment]
sure 😁
