### ISSUE TITLE
Molly get's unsuable after a while; losing connection to the Signal Account, no way to reconnect except reinstallation

### ISSUE THREAD

**Issue by Uneccessary** [mollyim/mollyim-android#265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

**Molly get's unable to receive messages or sync messages, showing if a person received a message or not, watching storys, checking Tor status (it shows a white exlamation mark, but when testing it says it's online)**

After a while Molly just randomly disconnects from the account in some way and get's unsuable, the only thing you can do is sending messages, but besides that nothing works.

**Following attempts to fix this issue did not work:**

- Reinstallation (only fixed it temporarly)
- Force stopping, cleaning cache
- Disabling/Enabling Database protection
- Disabling / Enabling Tor over Orbot
- Disabling / Enabling Tor over Socks5
- Schwitching between Molly-Foss, Molly-unfified and Molly (non-foss)

(I can provide debug logs, abt each case if needed)

### Steps to reproduce

1. Use Molly as usual
2. After 1-2 weeks it will stop working

### Molly version

v6.41.3-2-Foss / v6.41.3-2

### Android version

Android 14

### Device

Samsung

### Link to debug log

https://debuglogs.org/android/6.41.3/f4f515488669f204e726cbc88d11932c804f7bed43830e166004fe939c00da3b

**Comment by taivlam** [comment]
@Uneccessary To be clear, is this happening on the main Molly/Signal device?  (Just to make sure this isn't the same as issue #259.)

**Comment by Uneccessary** [comment]
Yes, it's the main device which is affected.

**Comment by taivlam** [comment]
Thanks, that clears things up - Molly on my main Android device is not disconnecting from Signal account, so this issue is different from mine.

**Comment by java-py-c-cpp-js** [comment]
I think you have mixed up the issue of [Uneccessary](https://github.com/Uneccessary) and of [taivlam](https://github.com/taivlam):
Uneccessary has created this issue and this issue is no duplicate of https://github.com/mollyim/mollyim-android/issues/259. 

taivlam has asked if the issue of Uneccessary is the same, but its not - it is not this issue and it is a duplicate - but *this* issue here (265) is the issue of Uneccessary - so the duplicate should be removed.

By the way: I have the same issue as Uneccessary today (without tor) so maybe it is not fixed as the other issue https://github.com/mollyim/mollyim-android/issues/259 .
