### ISSUE TITLE
Missing "Screen lock inactivity timeout"

### ISSUE THREAD

**Issue by schklom** [mollyim/mollyim-android#279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

In the "Privacy" settings, Signal has a configurable "Screen lock inactivity timeout", Molly does not for some reason.

### Steps to reproduce

1. Open Privacy in the settings
2. "Screen lock inactivity timeout" is missing below "Screen lock"

### Molly version

~v6.45.2-1.up1-FOSS~ EDIT: v6.47.4-1.up1-FOSS

### Android version

14

### Device

Pixel 6a

**Comment by valldrac** [comment]
The biometric screen lock in Molly works in a different way. Unlike Signal, there's no option to setup the timeout for the screen lock. This is because Molly already has a timeout for the database encryption, and having two different timeouts with different security properties would just confuse users. For more details on how it works, check out this link: https://github.com/mollyim/mollyim-android/pull/104.

**Comment by schklom** [comment]
> having two different timeouts with different security properties would just confuse users

I disagree. The lack of parity with the Signal app confused me. I used to have it set to 1 minute, 5 seconds is way too short.
Your concern could be resolved by adding a line of text saying that this timeout is distinct from the database encryption, couldn't it?

I will keep using this fantastic app anyway (and thanks for your work by the way, I cannot emphasize this enough!), but I always get surprised when features are actively removed. One usual benefit of open-source apps and their forks is that they add features, not remove them.
