### ISSUE TITLE
Locking database kills the notification service on FOSS version

### ISSUE THREAD

**Issue by Mattrazol** [mollyim/mollyim-android#31]
I noticed that when the database gets locked the notification service gets killed too. I wonder if this is a bug or if it's the expected behavior.
If this is expected, how would the phone be able to receive notifications?

**Comment by valldrac** [comment]
Yes, it's the expected behavior. See [this comment](https://github.com/mollyim/mollyim-android/issues/13#issuecomment-696646034) why.

My only advice right now is to not lock the database unless really needed. And set the lock timeout to a higher interval. You can configure it in the privacy settings.

There are some ideas to better handle notifications while locked. But nothing has been decided yet.
