### ISSUE TITLE
fdroid repository

### ISSUE THREAD

**Issue by John3** [mollyim/mollyim-android#32]
Good work on this fork man 👍 I not sure why you have two fdroid repos, does it have any benefits that I don't know about? 

You think is possible to add just one repo? using the same name except for the foss should be molly-foss to share the same repo 😄 

Other thing I notice molly is not in the "categories" section of fdroid.

**Comment by valldrac** [comment]
> Good work on this fork man

Thank you :heart: 

> I not sure why you have two fdroid repos, does it have any benefits that I don't know about?

Molly and Molly-FOSS have the same package ID and version code. They cannot be put together in the same repository. Otherwise fdroid will get confused.

One key reason to share the IDs is to share the application data, and thus avoid backup and restore when switching between Molly flavors.

> Other thing I notice molly is not in the "categories" section of fdroid.

I'm not sure what this means. Molly is already declared in 4 categories:
- Connectivity
- Phone & SMS
- Internet
- Security

**Comment by John3** [comment]
ok thank you for the clarification about the IDs 😅 

I wrote this [I'm using the foss version I can't find molly in any categories except if I search for it or use some key words.] at the same time I was trying to refresh the repo, I disabled and enabled the repo, now I can see molly on those categories. 

Not sure what happened when I tested molly at some point I enabled both repos and try both version, probably without refreshing correctly I think, and probably --> "Otherwise fdroid will get confused."

Anyhow thanks valldrac ;)
