### ISSUE TITLE
Export messages to a standard unencrypted SMS backup

### ISSUE THREAD

**Issue by emmatebibyte** [mollyim/mollyim-android#65]
This may be niche, but I hate being locked into the signal ecosystem, so it would be nice to have this feature available.

**Comment by valldrac** [comment]
Thanks for the suggestion. There are already some projects to export Signal backup files into CSV. Because Molly backups are compatible with Signal, they should work fine with Molly too.

I never used it, but check this tool https://github.com/pajowu/signal-backup-decode

In any case, it is better to implement this functionality in a separate tool from the main app.

**Comment by emmatebibyte** [comment]
Thank you!
